version: "3.8"

services:

  config-server:
    container_name: config-server
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    networks:
      store-network:
        aliases:
          - config-server

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      store-network:
        aliases:
          - eureka-server

  gateway:
    container_name: gateway
    build:
      context: ./gateway
    ports:
      - "8989:8989"
    depends_on:
      - config-server
      - keycloak
    networks:
      store-network:
        aliases:
          - gateway

  ms-product:
    container_name: ms-product
    build:
      context: ./ms-product
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - productdb
      - keycloak
    networks:
      store-network:
        aliases:
          - ms-product

  productdb:
    image: mongo:latest
    container_name: productdb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - productdb_data:/data/db
    restart: on-failure
    networks:
      store-network:
        aliases:
          - productdb

  ms-manufacturer:
    container_name: ms-manufacturer
    build:
      context: ./ms-manufacturer
    ports:
      - "8083:8083"
    depends_on:
      - config-server
      - manufacturerdb
      - keycloak
    networks:
      store-network:
        aliases:
          - ms-manufacturer

  manufacturerdb:
    image: mysql:8.0
    container_name: manufacturerdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: manufacturer_db
    ports:
      - "3306:3306"
    volumes:
      - manufacturerdb_data:/var/lib/mysql
    restart: on-failure
    networks:
      store-network:
        aliases:
          - manufacturerdb

  keycloakdb:
    image: postgres
    container_name: keycloakdb
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - keycloakdb_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      store-network:
        aliases:
          - keycloakdb

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
    command: start-dev
    depends_on:
      - keycloakdb
    ports:
      - "18080:8080"
    restart: on-failure
    networks:
      store-network:
        aliases:
          - keycloak

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: on-failure
    networks:
      store-network:
        aliases:
          - mail-dev

volumes:
  keycloakdb_data:
  manufacturerdb_data:
  productdb_data:

networks:
  store-network:
    driver: bridge
