apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: default
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: localhost:5000/eureka-server:latest
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_PROFILES_ACTIVE
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "false"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "false"
        - name: EUREKA_SERVER_ENABLE_SELF_PRESERVATION
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: EUREKA_SERVER_ENABLE_SELF_PRESERVATION
        - name: EUREKA_SERVER_REPLICATION_ENABLED
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: EUREKA_SERVER_REPLICATION_ENABLED
        - name: EUREKA_SERVER_DEFAULT_ZONE
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: EUREKA_SERVER_DEFAULT_ZONE
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: default
  labels:
    app: eureka-server
spec:
  type: ClusterIP
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
  selector:
    app: eureka-server
