apiVersion: apps/v1
kind: Deployment
metadata:
  name: productdb
  namespace: default
  labels:
    app: productdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productdb
  template:
    metadata:
      labels:
        app: productdb
    spec:
      containers:
      - name: productdb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: MONGO_INITDB_ROOT_PASSWORD
        volumeMounts:
        - name: productdb-storage
          mountPath: /data/db
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: productdb-storage
        persistentVolumeClaim:
          claimName: productdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: productdb
  namespace: default
  labels:
    app: productdb
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: productdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: productdb-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi