apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-notification
  namespace: default
  labels:
    app: ms-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-notification
  template:
    metadata:
      labels:
        app: ms-notification
    spec:
      containers:
      - name: ms-notification
        image: localhost:5000/ms-notification:latest
        ports:
        - containerPort: 8040
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_PROFILES_ACTIVE
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: CONFIG_SERVER_URL
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: EUREKA_CLIENT_REGISTER_WITH_EUREKA
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: EUREKA_CLIENT_FETCH_REGISTRY
        - name: SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
        - name: SPRING_MAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_MAIL_HOST
        - name: SPRING_MAIL_PORT
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_MAIL_PORT
        - name: SPRING_MAIL_USERNAME
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_MAIL_USERNAME
        - name: SPRING_MAIL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_MAIL_PASSWORD
        - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
        - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
        - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED
        - name: SPRING_MAIL_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_MAIL_PROTOCOL
        - name: KEYCLOAK_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: KEYCLOAK_SERVER_URL
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-notification
  namespace: default
  labels:
    app: ms-notification
spec:
  type: ClusterIP
  ports:
  - port: 8040
    targetPort: 8040
    protocol: TCP
  selector:
    app: ms-notification
