apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: default
data:
  # Spring Boot services configuration
  SPRING_PROFILES_ACTIVE: "default"
  CONFIG_SERVER_URL: "http://config-server:8888"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://eureka-server:8761/eureka"
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  EUREKA_CLIENT_FETCH_REGISTRY: "true"
  EUREKA_SERVER_ENABLE_SELF_PRESERVATION: "false"
  EUREKA_SERVER_REPLICATION_ENABLED: "true"
  EUREKA_SERVER_DEFAULT_ZONE: "http://eureka-server:8761/eureka/"
  
  # Database connections
  SPRING_DATA_MONGODB_URI: "mongodb://productdb:27017/product_db"
  SPRING_DATASOURCE_URL: "jdbc:mysql://manufacturerdb:3306/manufacturer_db"
  SPRING_DATASOURCE_USERNAME: "root"
  
  # Kafka configuration
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:19092"
  SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: "kafka:19092"
  SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS: "kafka:19092"
  
  # Mail configuration
  SPRING_MAIL_HOST: "mail-dev"
  SPRING_MAIL_PORT: "1025"
  SPRING_MAIL_USERNAME: ""
  SPRING_MAIL_PASSWORD: ""
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "false"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: "false"
  SPRING_MAIL_PROTOCOL: "smtp"
  
  # Keycloak configuration
  KEYCLOAK_SERVER_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "authentication"
  KEYCLOAK_CLIENT_ID: "store-app"
  KEYCLOAK_USERNAME: "admin"
  
  # Authentication service configuration
  PORT: "5050"
