apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloakdb
  namespace: default
  labels:
    app: keycloakdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloakdb
  template:
    metadata:
      labels:
        app: keycloakdb
    spec:
      containers:
      - name: keycloakdb
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: keycloakdb-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: keycloakdb-storage
        persistentVolumeClaim:
          claimName: keycloakdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: keycloakdb
  namespace: default
  labels:
    app: keycloakdb
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: keycloakdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloakdb-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
