apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-product
  namespace: default
  labels:
    app: ms-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-product
  template:
    metadata:
      labels:
        app: ms-product
    spec:
      containers:
      - name: ms-product
        image: localhost:5000/ms-product:latest
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_PROFILES_ACTIVE
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: CONFIG_SERVER_URL
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: EUREKA_CLIENT_REGISTER_WITH_EUREKA
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: EUREKA_CLIENT_FETCH_REGISTRY
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_DATA_MONGODB_URI
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: KEYCLOAK_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: KEYCLOAK_SERVER_URL
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-product
  namespace: default
  labels:
    app: ms-product
spec:
  type: ClusterIP
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
  selector:
    app: ms-product
