server:
  port: 8081

spring:
  application:
    name: ms-product

  
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         issuer-uri: http://localhost:18080/realms/authentication
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ms_product
      username: root
      password: root
      authentication-database: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

# keycloak credentials
keycloak:
  auth-server-url: http://localhost:18080
  realm: camp-esprit
  resource: express-app
  secret: v0gREWBMXdIhgTI6GBkfzhcO5AcspCMK
  bearer-only: true

logging:
  level:
    com.store.product: DEBUG
