server:
  port: 8083

spring:
  application:
    name: ms-manufacturer

  datasource:
    url: jdbc:mysql://localhost:3306/manufacturer_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  
  # security:
  #   oauth2:
  #     resourceserveycer: 
  #       jwt:  
  #         issuer-uri: http://localhost:18080/realms/authentication

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

# keycloak credentials
keycloak:
  auth-server-url: http://localhost:18080
  realm: camp-esprit
  resource: express-app
  secret: v0gREWBMXdIhgTI6GBkfzhcO5AcspCMK
  bearer-only: true

logging:
  level:
    com.store.manufacturer: DEBUG
